meta_product_name: "Blabla'sloop"
 meta_title: "Blabla'sloop - Mettez votre bilan carbone sur une voile"
 meta_description: "Découvrez une nouvelle façon de voyager éco-responsable avec notre application de co-navigation en bateau à voile. Partagez des aventures en mer, connectez-vous avec des passionnés, tout en réduisant votre impact écologique. Naviguez de manière conviviale, respectueuse de l'environnement et humaine, en rejoignant notre communauté de marins engagés."
 meta_image: "cover.png" # should exist in `app/assets/images/`
 twitter_account: "@product_twitter_account" # required for Twitter Cards


# config/initializers/default_meta.rb
# Initialiser les balises méta par défaut.

DEFAULT_META = YAML.load_file(Rails.root.join("config/meta.yml"))
